# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3adb9f07a1c4eaf57ab1ac837498fc352e8441d70375bffdf4c766978509d317306018015648ed6263684ae916ec25116d724225ac43cc104d74e1a8519831

test:
  secret_key_base: 14e0877e7f334b175869224c8d7cbbc2b60ef7c3e42e36195583bfe2eaca8565b5155e4aca47272660b2f4c05a97457f0bec89c9b9020e26a36324507380b044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
